### ISSUE TITLE
getCurrentView() hang when I run multi test function in one class.

### ISSUE THREAD

**Issue by Mrxiaoxie** [RobotiumTech/robotium#837]
Here is the situation:
I write test function and make sure it works. So I try to run multi test function,  In the second of test function process, I found the application doesn't response. so I try to find out. I add some log like above.
Log.e("KuaiXiao", "before get currentActivity");
Activity activity = solo.getCurrentActivity();
Log.e("KuaiXiao", "after get currentActivity");
the logcat did print "before get currentActivity" but didn't print "after get currentActivity".So I check the code. and I try to use solo.getActivityMonitor().getLastActivity() to see what I get. the result of it is an exception that java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity android.app.Instrumentation$ActivityMonitor.getLastActivity()' on a null object reference

I'm confused. why the activityMonitor is null ?

what's the diference between single test function run and multi test function run ?

here is my setUp() and tearDown()：
```
@Override
public void setUp(){
		Config config = new Config();
		config.commandLogging = true;
		config.commandLoggingTag = "TAG";
		config.screenshotFileType = ScreenshotFileType.PNG;
		config.screenshotSavePath = Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "robotium" + File.separator + System.currentTimeMillis();
		config.timeout_large = 20000;
		config.timeout_small = 10000;
		config.shouldScroll = true;
		config.trackActivities = true;
		instrumentation = getInstrumentation();
		solo = new Solo(instrumentation, config, getActivity());
		soloUtils = SoloUtils.getInstance(solo, instrumentation);
		logger = Logger.getLogger(VisitTest.class);
	}
```
teardown:	
```
@Override
public void tearDown(){
	solo.takeScreenshot();
	solo.finishOpenedActivities();
	try {
		try {
			solo.finalize();
		} catch (Throwable e) {
			//TODO Auto-generated catch block
			e.printStackTrace();
		}
		super.tearDown();
	} catch (Exception e) {
		logger.debug("teardown fail:" + e);
	}
}
```

**Comment by Mrxiaoxie** [comment]
anybody have any ideas?  share with me, thank you in advance

**Comment by SKART1** [comment]
Please use code tags from markdown

Our company faced same issue - random hanging batch of multiactivity tests. Firstly I have found when enabling "Do not keep activities" in Android: Settings -> Developer Options helps to reproduce this bug more often

As I understood it happens because previous activity was not killed when new intent for launching new have come. But may be I am wrong

Please check with "Do not keep activities"  flag

**Comment by Mrxiaoxie** [comment]
Thank you for your reply. but the tests still hang no matter enabling or disabling "Do not keep activities".I have searched the question  with google, got the reason as you mentioned and tried to use the methods to solve it. But they didn't work and I'm puzzled.

**Comment by SKART1** [comment]
@Mrxiaoxie I have mentioned "Do not keep activities" because it makes problem even **worse** so it will be easy to understand what is going wrong (by attaching to device with debugger and making thread dump for example).
But I think you will see something like this:

```java
"Instr: com.android.test.runner.MultiDexTestRunner@5695" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Instr: com.android.test.runner.MultiDexTestRunner@5695
	  at java.lang.Object.wait(Object.java:-1)
	  at android.app.Instrumentation.startActivitySync(Instrumentation.java:410)
	  - locked <0x1b25> (a java.lang.Object)
	  at android.test.InstrumentationTestCase.launchActivityWithIntent(InstrumentationTestCase.java:119)
	  at android.test.InstrumentationTestCase.launchActivity(InstrumentationTestCase.java:97)
	  at android.test.ActivityInstrumentationTestCase2.getActivity(ActivityInstrumentationTestCase2.java:104)
	  at %MY_COMPANYDOMAIN%.core.ActivityTestCase2.getActivity(ActivityTestCase2.java:125)
	  at %MY_COMPANYDOMAIN%.core.ActivityTestCase2.setUp(ActivityTestCase2.java:31)
	  at junit.framework.TestCase.runBare(TestCase.java:132)
	  at junit.framework.TestResult$1.protect(TestResult.java:115)
	  at junit.framework.TestResult.runProtected(TestResult.java:133)
	  at junit.framework.TestResult.run(TestResult.java:118)
	  at junit.framework.TestCase.run(TestCase.java:124)
	  at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
	  at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
	  at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
	  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1886)
```

At the same time I can see activity launched by previous test


You may try workaround (I am not sure about this) to add Thread.sleep() for example for 10-30 seconds after each test - and see if this will help


As in our company we have solved this (and other problems related to tests - like crashing of the app main thread causing test run to stop, or crashing in native code of android framework which also results in broken test run) by creating system which launch test just one by one

**Comment by Mrxiaoxie** [comment]
Thank you for your help.  I have find that it's my mistake. I make the Class SoloUtils Singleton. After the first test function ran. solo finalized. and so soloUtils still use the finalized solo when the next test function run.
Again, Thank you for your help.
